set search_path = 'Project';
drop table db_user cascade;
drop table food cascade;
drop table ingredient_for cascade;
drop table ingredient_order cascade;
drop table meal cascade;
drop table meal_request cascade;
drop table order_contains cascade;
drop table category cascade;